fix "no attribute 'RMSPropOptimizer'" error basic_regression.ipynb
While searching for a simple demo of basic-regression I came across this, but until I made the following change to basic_regression.ipynb 

optimizer = tf.train.RMSPropOptimizer(0.001)
   to
optimizer = tf.keras.optimizers.RMSprop()

I would get 
  AttributeError: module 'tensorflow._api.v2.train' has no attribute 'RMSPropOptimizer'

with tf.__version__ == "2.4.1"